# Use Alpine Linux as base image
FROM alpine:latest

# Set up a directory for scripts
WORKDIR /app

# Set environment variables using build arguments
ARG CD_CODEBUILD_BATCH_BUILD_IDENTIFIER
ARG CD_CODEBUILD_BUILD_ARN
ARG CD_CODEBUILD_BUILD_ID
ARG CD_CODEBUILD_BUILD_IMAGE
ARG CD_CODEBUILD_BUILD_NUMBER
ARG CD_CODEBUILD_BUILD_SUCCEEDING
ARG CD_CODEBUILD_INITIATOR
ARG CD_CODEBUILD_RESOLVED_SOURCE_VERSION
ARG CD_CODEBUILD_SOURCE_REPO_URL
ARG CD_CODEBUILD_SOURCE_VERSION
ARG CD_CODEBUILD_START_TIME

ENV CD_CODEBUILD_BATCH_BUILD_IDENTIFIER=$CD_CODEBUILD_BATCH_BUILD_IDENTIFIER \
    CD_CODEBUILD_BUILD_ARN=$CD_CODEBUILD_BUILD_ARN \
    CD_CODEBUILD_BUILD_ID=$CD_CODEBUILD_BUILD_ID \
    CD_CODEBUILD_BUILD_IMAGE=$CD_CODEBUILD_BUILD_IMAGE \
    CD_CODEBUILD_BUILD_NUMBER=$CD_CODEBUILD_BUILD_NUMBER \
    CD_CODEBUILD_BUILD_SUCCEEDING=$CD_CODEBUILD_BUILD_SUCCEEDING \
    CD_CODEBUILD_INITIATOR=$CD_CODEBUILD_INITIATOR \
    CD_CODEBUILD_RESOLVED_SOURCE_VERSION=$CD_CODEBUILD_RESOLVED_SOURCE_VERSION \
    CD_CODEBUILD_SOURCE_REPO_URL=$CD_CODEBUILD_SOURCE_REPO_URL \
    CD_CODEBUILD_SOURCE_VERSION=$CD_CODEBUILD_SOURCE_VERSION \
    CD_CODEBUILD_START_TIME=$CD_CODEBUILD_START_TIME

# Print the injected environment variables
CMD echo "CD_CODEBUILD_BATCH_BUILD_IDENTIFIER is $CD_CODEBUILD_BATCH_BUILD_IDENTIFIER" && \
    echo "CD_CODEBUILD_BUILD_ARN is $CD_CODEBUILD_BUILD_ARN" && \
    echo "CD_CODEBUILD_BUILD_ID is $CD_CODEBUILD_BUILD_ID" && \
    echo "CD_CODEBUILD_BUILD_IMAGE is $CD_CODEBUILD_BUILD_IMAGE" && \
    echo "CD_CODEBUILD_BUILD_NUMBER is $CD_CODEBUILD_BUILD_NUMBER" && \
    echo "CD_CODEBUILD_BUILD_SUCCEEDING is $CD_CODEBUILD_BUILD_SUCCEEDING" && \
    echo "CD_CODEBUILD_INITIATOR is $CD_CODEBUILD_INITIATOR" && \
    echo "CD_CODEBUILD_RESOLVED_SOURCE_VERSION is $CD_CODEBUILD_RESOLVED_SOURCE_VERSION" && \
    echo "CD_CODEBUILD_SOURCE_REPO_URL is $CD_CODEBUILD_SOURCE_REPO_URL" && \
    echo "CD_CODEBUILD_SOURCE_VERSION is $CD_CODEBUILD_SOURCE_VERSION" && \
    echo "CD_CODEBUILD_START_TIME is $CD_CODEBUILD_START_TIME"
