FROM public.ecr.aws/docker/library/busybox:stable-musl

# Define build arguments
ARG CD_CODEBUILD_BATCH_BUILD_IDENTIFIER
ARG CD_CODEBUILD_BUILD_ARN
ARG CD_CODEBUILD_BUILD_ID
ARG CD_CODEBUILD_BUILD_IMAGE
ARG CD_CODEBUILD_BUILD_NUMBER
ARG CD_CODEBUILD_BUILD_SUCCEEDING
ARG CD_CODEBUILD_INITIATOR
ARG CD_CODEBUILD_RESOLVED_SOURCE_VERSION
ARG CD_CODEBUILD_SOURCE_REPO_URL
ARG CD_CODEBUILD_SOURCE_VERSION
ARG CD_CODEBUILD_START_TIME
ARG CD_COMMIT_MESSAGE

# Set environment variables from build arguments
ENV CD_CODEBUILD_BATCH_BUILD_IDENTIFIER=$CD_CODEBUILD_BATCH_BUILD_IDENTIFIER
ENV CD_CODEBUILD_BUILD_ARN=$CD_CODEBUILD_BUILD_ARN
ENV CD_CODEBUILD_BUILD_ID=$CD_CODEBUILD_BUILD_ID
ENV CD_CODEBUILD_BUILD_IMAGE=$CD_CODEBUILD_BUILD_IMAGE
ENV CD_CODEBUILD_BUILD_NUMBER=$CD_CODEBUILD_BUILD_NUMBER
ENV CD_CODEBUILD_BUILD_SUCCEEDING=$CD_CODEBUILD_BUILD_SUCCEEDING
ENV CD_CODEBUILD_INITIATOR=$CD_CODEBUILD_INITIATOR
ENV CD_CODEBUILD_RESOLVED_SOURCE_VERSION=$CD_CODEBUILD_RESOLVED_SOURCE_VERSION
ENV CD_CODEBUILD_SOURCE_REPO_URL=$CD_CODEBUILD_SOURCE_REPO_URL
ENV CD_CODEBUILD_SOURCE_VERSION=$CD_CODEBUILD_SOURCE_VERSION
ENV CD_CODEBUILD_START_TIME=$CD_CODEBUILD_START_TIME
ENV CD_CD_COMMIT_MESSAGE=$CD_CD_COMMIT_MESSAGE


# Print the environment variables to verify
RUN echo "CD_CODEBUILD_BATCH_BUILD_IDENTIFIER: $CD_CODEBUILD_BATCH_BUILD_IDENTIFIER" && \
    echo "CD_CODEBUILD_BUILD_ARN: $CD_CODEBUILD_BUILD_ARN" && \
    echo "CD_CODEBUILD_BUILD_ID: $CD_CODEBUILD_BUILD_ID" && \
    echo "CD_CODEBUILD_BUILD_IMAGE: $CD_CODEBUILD_BUILD_IMAGE" && \
    echo "CD_CODEBUILD_BUILD_NUMBER: $CD_CODEBUILD_BUILD_NUMBER" && \
    echo "CD_CODEBUILD_BUILD_SUCCEEDING: $CD_CODEBUILD_BUILD_SUCCEEDING" && \
    echo "CD_CODEBUILD_INITIATOR: $CD_CODEBUILD_INITIATOR" && \
    echo "CD_CODEBUILD_RESOLVED_SOURCE_VERSION: $CD_CODEBUILD_RESOLVED_SOURCE_VERSION" && \
    echo "CD_CODEBUILD_SOURCE_REPO_URL: $CD_CODEBUILD_SOURCE_REPO_URL" && \
    echo "CD_CODEBUILD_SOURCE_VERSION: $CD_CODEBUILD_SOURCE_VERSION" && \
    echo "CD_CODEBUILD_START_TIME: $CD_CODEBUILD_START_TIME" && \
    echo "CD_CD_COMMIT_MESSAGE: $CD_CD_COMMIT_MESSAGE"
    

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
